### ISSUE TITLE
In a desktop browser, newer vods are listed last

### ISSUE THREAD

**Issue by garoto** [madiele/TwitchToPodcastRSS#4]
Can it it be made so that the default order is newer->older, like in Izeke0's appspot feed?

Adding screenshot to demonstrate what I see in the browser:

![screenshot-0710-23-08-2021](https://user-images.githubusercontent.com/11768175/130488367-2e85f5e5-de82-478e-ad3a-a2a9d2157b5f.png)

**Comment by madiele** [comment]
probably due to the fact that I switched library for the feed generation, should be an easy fix I'll look in to it later

**Comment by madiele** [comment]
not only I fixed the issue but I also added a sort_by and desc option to sort by any key listed in the twitch response

the list of keys to sort by can be found [here](https://dev.twitch.tv/docs/api/reference#get-videos) in the response field section

by default it sorts by the published_at field

to enable sorting just add `sort_by=[key]` or/and `desc=True` to the URL

some example:

to sort by views:

`myserver.com/vod/kasparovchess?sort_by=view_count`

to sort by views descending:

`myserver.com/vod/kasparovchess?sort_by=view_count&desc=true`

I will update the docker images later today

**Comment by garoto** [comment]
Fantastic! Just tested the new sorting option and `?links_only=True` and all is working great as far as I was able to test. Much appareciated!
